### ISSUE TITLE
Logs plugin generated a warning from the characteristic 

### ISSUE THREAD

**Issue by willyhabr** [ttimpe/homebridge-midea#42] opened 2021-02-24 20:46 UTC
Get some errors messages on HOMEBRIDGE logs:

 [homebridge-midea] This plugin generated a warning from the characteristic 'Active': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
Can you help to solve this?

**Comment by RaziAmin** [comment] 2021-04-23 05:21
It seems like Midea has changed its API behaviors, I guess the developer will need to check the API responses.

one major change I've noticed: You don't need to add the devices manually now, putting your username and password in the plugin will automatically pull all devices you have in your account and gets populated on HomeKit.

so my sense here is that the plugin will need some tuning.

**Comment by arek190491** [comment] 2021-07-13 22:26
Day after day, midea homebridge plugin stop working. 
In hombirdge log i have information
"This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 10. See https://git.io/JtMGR for more info."

The plugin properly logon to my midea account, but i can't nothing to do with my AC in HOME APP...

**Comment by ttimpe** [comment] 2021-07-26 20:14
Duplicate of #46
As for @arek190491's issue, I honestly have no (M)idea, how their API actually works and I only have one model of AC from them (although that may change soon). So I can't debug any of your hardware not working with the plugin. If you're feeling adventurous, have a look for yourself :)

**Closed by ttimpe** 2021-07-26 20:14 UTC
Labels: duplicate
