### ISSUE TITLE
Threshold Value Error

### ISSUE THREAD

**Issue by pichol** [ttimpe/homebridge-midea#41] opened 2021-02-24 19:56 UTC
I am getting a threshold error, and I've seen that the AC starts with 0ºC, the minimum on my units being 17...

[homebridge-midea] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 10. See https://git.io/JtMGR for more info.

AC Midea Carrier with Dongle Wi-Fi Firmware version 056004051538.

**Comment by Paulxp** [comment] 2021-02-25 19:50
I have the same issue...

**Comment by ttimpe** [comment] 2021-07-26 20:15
Duplicate of #46

**Closed by ttimpe** 2021-07-26 20:15 UTC
Labels: duplicate
