### ISSUE TITLE
When adjusting temperature - it sets unit to celsius

### ISSUE THREAD

**Issue by jasonliehr** [ttimpe/homebridge-midea#27] opened 2020-09-13 00:45 UTC
Having an issue with MAW12V1QWT. When adjusting temperature using home app it sets the unit to celsius on the ac unit.

**Comment by jackklink** [comment] 2020-10-24 19:29
Having the same issue. The config for this needs Fahrenheit option for us American weirdos :)

**Comment by madmarf** [comment] 2020-12-14 19:02
Hello, this is funny. I got the bug inverted. I set the Temp in C in Homekit, but shows Temp in F at the unit. But when i control direct on the unit it switches back to C.
Is there a bug in the config where the parameters are crossed?

**Comment by ttimpe** [comment] 2020-12-16 13:27
It's due to the API not being publicly documented.

**Comment by ttimpe** [comment] 2020-12-16 13:28
Duplicate of #11

**Closed by ttimpe** 2020-12-16 13:28 UTC
Labels: API-related, bug
